version: "3.9"

services:

  web:
    container_name: nginx
    image: nginx:stable
    depends_on:
      - php
      - db
    working_dir: /var/www/html/
    ports:
      - "8080:80"
    volumes:
      - ../project:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    container_name: php-fpm81
    hostname: php-docker-service
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - ../project:/var/www/html
      - ./docker/docker-xdebug-php.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
      XDEBUG_SESSION: 1
      XDEBUG_CONFIG: 1

  db:
      container_name: postgres
      depends_on:
          - php
      image: postgres:14
      restart: always
      environment:
          DB_CONNECTION: pgsql
          POSTGRES_DB: testdb
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          PGDATA: "/var/lib/postgresql/data/pgdata"
      volumes:
          - ./database:/var/lib/postgresql/data
      ports:
          - 5432:5432

